package POJOs;
// Generated 9/10/2023 01:23:50 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleVenta generated by hbm2java
 */
public class DetalleVenta  implements java.io.Serializable {


     private Integer idDetalleVenta;
     private Producto producto;
     private Venta venta;
     private Integer cantidad;
     private BigDecimal monto;

    public DetalleVenta() {
    }

    public DetalleVenta(Producto producto, Venta venta, Integer cantidad, BigDecimal monto) {
       this.producto = producto;
       this.venta = venta;
       this.cantidad = cantidad;
       this.monto = monto;
    }
   
    public Integer getIdDetalleVenta() {
        return this.idDetalleVenta;
    }
    
    public void setIdDetalleVenta(Integer idDetalleVenta) {
        this.idDetalleVenta = idDetalleVenta;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }




}


