package POJOs;
// Generated 27/10/2023 03:26:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleCompra generated by hbm2java
 */
public class DetalleCompra  implements java.io.Serializable {


     private int idDetalleCompra;
     private Compra compra;
     private Producto producto;
     private Integer cantidad;
     private BigDecimal monto;

    public DetalleCompra() {
    }

	
    public DetalleCompra(int idDetalleCompra) {
        this.idDetalleCompra = idDetalleCompra;
    }
    public DetalleCompra(int idDetalleCompra, Compra compra, Producto producto, Integer cantidad, BigDecimal monto) {
       this.idDetalleCompra = idDetalleCompra;
       this.compra = compra;
       this.producto = producto;
       this.cantidad = cantidad;
       this.monto = monto;
    }
   
    public int getIdDetalleCompra() {
        return this.idDetalleCompra;
    }
    
    public void setIdDetalleCompra(int idDetalleCompra) {
        this.idDetalleCompra = idDetalleCompra;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }




}


