package POJOs;
// Generated 29/10/2023 02:21:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoPago generated by hbm2java
 */
public class TipoPago  implements java.io.Serializable {


     private Integer idTipoPago;
     private Boolean estado;
     private String nombre;
     private Set<Compra> compras = new HashSet<Compra>(0);
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public TipoPago() {
    }

    public TipoPago(Boolean estado, String nombre, Set<Compra> compras, Set<Venta> ventas) {
       this.estado = estado;
       this.nombre = nombre;
       this.compras = compras;
       this.ventas = ventas;
    }
   
    public Integer getIdTipoPago() {
        return this.idTipoPago;
    }
    
    public void setIdTipoPago(Integer idTipoPago) {
        this.idTipoPago = idTipoPago;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Compra> getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set<Compra> compras) {
        this.compras = compras;
    }
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }




}


