package POJOs;
// Generated 27/10/2023 03:26:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Rol rol;
     private Boolean estado;
     private String nombre;
     private String contrasenia;
     private Set<Proveedor> proveedorsForUsuarioModifica = new HashSet<Proveedor>(0);
     private Set<Proveedor> proveedorsForUsuarioIngresa = new HashSet<Proveedor>(0);
     private Set<Cliente> clientesForUsuarioIngresa = new HashSet<Cliente>(0);
     private Set<Producto> productosForUsuarioModifica = new HashSet<Producto>(0);
     private Set<Cliente> clientesForUsuarioModifica = new HashSet<Cliente>(0);
     private Set<Producto> productosForUsuarioIngresa = new HashSet<Producto>(0);
     private Set<Venta> ventasForUsuarioIngresa = new HashSet<Venta>(0);
     private Set<Venta> ventasForUsuarioModifica = new HashSet<Venta>(0);
     private Set<Compra> comprasForUsuarioModifica = new HashSet<Compra>(0);
     private Set<Compra> comprasForUsuarioIngresa = new HashSet<Compra>(0);

    public Usuario() {
    }

	
    public Usuario(Rol rol) {
        this.rol = rol;
    }
    public Usuario(Rol rol, Boolean estado, String nombre, String contrasenia, Set<Proveedor> proveedorsForUsuarioModifica, Set<Proveedor> proveedorsForUsuarioIngresa, Set<Cliente> clientesForUsuarioIngresa, Set<Producto> productosForUsuarioModifica, Set<Cliente> clientesForUsuarioModifica, Set<Producto> productosForUsuarioIngresa, Set<Venta> ventasForUsuarioIngresa, Set<Venta> ventasForUsuarioModifica, Set<Compra> comprasForUsuarioModifica, Set<Compra> comprasForUsuarioIngresa) {
       this.rol = rol;
       this.estado = estado;
       this.nombre = nombre;
       this.contrasenia = contrasenia;
       this.proveedorsForUsuarioModifica = proveedorsForUsuarioModifica;
       this.proveedorsForUsuarioIngresa = proveedorsForUsuarioIngresa;
       this.clientesForUsuarioIngresa = clientesForUsuarioIngresa;
       this.productosForUsuarioModifica = productosForUsuarioModifica;
       this.clientesForUsuarioModifica = clientesForUsuarioModifica;
       this.productosForUsuarioIngresa = productosForUsuarioIngresa;
       this.ventasForUsuarioIngresa = ventasForUsuarioIngresa;
       this.ventasForUsuarioModifica = ventasForUsuarioModifica;
       this.comprasForUsuarioModifica = comprasForUsuarioModifica;
       this.comprasForUsuarioIngresa = comprasForUsuarioIngresa;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Set<Proveedor> getProveedorsForUsuarioModifica() {
        return this.proveedorsForUsuarioModifica;
    }
    
    public void setProveedorsForUsuarioModifica(Set<Proveedor> proveedorsForUsuarioModifica) {
        this.proveedorsForUsuarioModifica = proveedorsForUsuarioModifica;
    }
    public Set<Proveedor> getProveedorsForUsuarioIngresa() {
        return this.proveedorsForUsuarioIngresa;
    }
    
    public void setProveedorsForUsuarioIngresa(Set<Proveedor> proveedorsForUsuarioIngresa) {
        this.proveedorsForUsuarioIngresa = proveedorsForUsuarioIngresa;
    }
    public Set<Cliente> getClientesForUsuarioIngresa() {
        return this.clientesForUsuarioIngresa;
    }
    
    public void setClientesForUsuarioIngresa(Set<Cliente> clientesForUsuarioIngresa) {
        this.clientesForUsuarioIngresa = clientesForUsuarioIngresa;
    }
    public Set<Producto> getProductosForUsuarioModifica() {
        return this.productosForUsuarioModifica;
    }
    
    public void setProductosForUsuarioModifica(Set<Producto> productosForUsuarioModifica) {
        this.productosForUsuarioModifica = productosForUsuarioModifica;
    }
    public Set<Cliente> getClientesForUsuarioModifica() {
        return this.clientesForUsuarioModifica;
    }
    
    public void setClientesForUsuarioModifica(Set<Cliente> clientesForUsuarioModifica) {
        this.clientesForUsuarioModifica = clientesForUsuarioModifica;
    }
    public Set<Producto> getProductosForUsuarioIngresa() {
        return this.productosForUsuarioIngresa;
    }
    
    public void setProductosForUsuarioIngresa(Set<Producto> productosForUsuarioIngresa) {
        this.productosForUsuarioIngresa = productosForUsuarioIngresa;
    }
    public Set<Venta> getVentasForUsuarioIngresa() {
        return this.ventasForUsuarioIngresa;
    }
    
    public void setVentasForUsuarioIngresa(Set<Venta> ventasForUsuarioIngresa) {
        this.ventasForUsuarioIngresa = ventasForUsuarioIngresa;
    }
    public Set<Venta> getVentasForUsuarioModifica() {
        return this.ventasForUsuarioModifica;
    }
    
    public void setVentasForUsuarioModifica(Set<Venta> ventasForUsuarioModifica) {
        this.ventasForUsuarioModifica = ventasForUsuarioModifica;
    }
    public Set<Compra> getComprasForUsuarioModifica() {
        return this.comprasForUsuarioModifica;
    }
    
    public void setComprasForUsuarioModifica(Set<Compra> comprasForUsuarioModifica) {
        this.comprasForUsuarioModifica = comprasForUsuarioModifica;
    }
    public Set<Compra> getComprasForUsuarioIngresa() {
        return this.comprasForUsuarioIngresa;
    }
    
    public void setComprasForUsuarioIngresa(Set<Compra> comprasForUsuarioIngresa) {
        this.comprasForUsuarioIngresa = comprasForUsuarioIngresa;
    }




}


