package POJOs;
// Generated 29/10/2023 02:21:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer idVenta;
     private Cliente cliente;
     private TipoPago tipoPago;
     private Usuario usuarioByUsuarioIngresa;
     private Usuario usuarioByUsuarioModifica;
     private Boolean estado;
     private String nombre;
     private Boolean estadoFinalizado;
     private Date fechaVenta;
     private Date fechaIngresa;
     private Date fechaModifica;
     private Set<DetalleVenta> detalleVentas = new HashSet<DetalleVenta>(0);

    public Venta() {
    }

    public Venta(Cliente cliente, TipoPago tipoPago, Usuario usuarioByUsuarioIngresa, Usuario usuarioByUsuarioModifica, Boolean estado, String nombre, Boolean estadoFinalizado, Date fechaVenta, Date fechaIngresa, Date fechaModifica, Set<DetalleVenta> detalleVentas) {
       this.cliente = cliente;
       this.tipoPago = tipoPago;
       this.usuarioByUsuarioIngresa = usuarioByUsuarioIngresa;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.estado = estado;
       this.nombre = nombre;
       this.estadoFinalizado = estadoFinalizado;
       this.fechaVenta = fechaVenta;
       this.fechaIngresa = fechaIngresa;
       this.fechaModifica = fechaModifica;
       this.detalleVentas = detalleVentas;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public TipoPago getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(TipoPago tipoPago) {
        this.tipoPago = tipoPago;
    }
    public Usuario getUsuarioByUsuarioIngresa() {
        return this.usuarioByUsuarioIngresa;
    }
    
    public void setUsuarioByUsuarioIngresa(Usuario usuarioByUsuarioIngresa) {
        this.usuarioByUsuarioIngresa = usuarioByUsuarioIngresa;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Boolean getEstadoFinalizado() {
        return this.estadoFinalizado;
    }
    
    public void setEstadoFinalizado(Boolean estadoFinalizado) {
        this.estadoFinalizado = estadoFinalizado;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public Date getFechaIngresa() {
        return this.fechaIngresa;
    }
    
    public void setFechaIngresa(Date fechaIngresa) {
        this.fechaIngresa = fechaIngresa;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }
    public Set<DetalleVenta> getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set<DetalleVenta> detalleVentas) {
        this.detalleVentas = detalleVentas;
    }




}


